name: Daily Commit

on:
  schedule:
    - cron: '5 17 * * *'  # Adjust to your next test run
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make a change with email 24ds3000000@ds.study.iitm.ac.in
        run: |
          echo "Updated on $(date +%s)" >> daily.log

      - name: Commit and Push
        run: |
          git add daily.log
          git commit -m "Automated commit from workflow at $(date)" || echo "No changes to commit"
          git push
